---
- hosts: localhost
  connection: no
  gather_facts: no
  tasks:
  - name: print call msg
    debug:
      msg: "The device hostname is: {{ entry.hostname }}"
    loop: "{{ entries }}"
    loop_control:
      loop_var: entry

